module.exports = {

  templatesDirectory: require('path').resolve(__dirname, '../templates'),
  before: require('./before'),
  targets: {
    './app/helpers': {folder: {}},
    './app/mirage': {folder: {}},
    './app/mirage/factories': {folder: {}},
    './app/mirage/scenarios': {folder: {}},
    './app/routes': {folder: {}},
    './app/routes/about': {folder: {}},
    './app/routes/application': {folder: {}},
    './app/routes/components': {folder: {}},
    './app/routes/components/site-footer': {folder: {}},
    './app/routes/components/site-nav': {folder: {}},
    './app/routes/index': {folder: {}},
    './app/styles': {folder: {}},
    './config': {folder: {}},
    './public': {folder: {}},
    './public/images': {folder: {}},
    './tests/helpers': {folder: {}},
    './tests/integration': {folder: {}},
    './tests/integration/routes': {folder: {}},
    './tests/integration/routes/components': {folder: {}},
    './tests/unit/helpers': {folder: {}},
    './tests/unit/routes': {folder: {}},
    './vendor': {folder: {}},

    'app/app.js': {copy: 'app/app.js'},
    'app/index.html': {copy: 'app/index.html'},
    'app/resolver.js': {copy: 'app/resolver.js'},
    'app/router.js': {copy: 'app/router.js'},
    'app/helpers/eq.js': {copy: 'app/helpers/eq.js'},
    'app/helpers/icon.js': {copy: 'app/helpers/icon.js'},
    'app/helpers/pluralize.js': {copy: 'app/helpers/pluralize.js'},
    'app/styles/app.css': {copy: 'app/styles/app.css'},
    'app/mirage/config.js': {copy: 'app/mirage/config.js'},
    'app/mirage/factories/example.js': {copy: 'app/mirage/factories/example.js'},
    'app/mirage/scenarios/default.js': {copy: 'app/mirage/scenarios/default.js'},
    'app/routes/application/adapter.js': {copy: 'app/routes/application/adapter.js'},
    'app/routes/application/route.js': {copy: 'app/routes/application/route.js'},
    'app/routes/application/template.hbs': {copy: 'app/routes/application/template.hbs'},
    'app/routes/about/route.js': {copy: 'app/routes/about/route.js'},
    'app/routes/about/template.hbs': {copy: 'app/routes/about/template.hbs'},
    'app/routes/index/route.js': {copy: 'app/routes/index/route.js'},
    'app/routes/index/template.hbs': {copy: 'app/routes/index/template.hbs'},
    'app/routes/components/site-footer/component.js': {copy: 'app/routes/components/site-footer/component.js'},
    'app/routes/components/site-footer/template.hbs': {copy: 'app/routes/components/site-footer/template.hbs'},
    'app/routes/components/site-nav/component.js': {copy: 'app/routes/components/site-nav/component.js'},
    'app/routes/components/site-nav/template.hbs': {copy: 'app/routes/components/site-nav/template.hbs'},

    'config/environment.js': {copy: 'config/environment.js'},

    'public/crossdomain.xml': {copy: 'public/crossdomain.xml'},
    'public/robots.txt': {copy: 'public/robots.txt'},
    'public/images/media-paragraph.png': {copy: 'public/images/media-paragraph.png'},
    'public/images/white-image.png': {copy: 'public/images/white-image.png'},

    'vendor/.gitkeep': {copy: 'vendor/.gitkeep'},

    'tests/.jshintrc': {copy: 'tests/.jshintrc'},
    'tests/index.html': {copy: 'tests/index.html'},
    'tests/test-helper.js': {copy: 'tests/test-helper.js'},
    'tests/helpers/destroy-app.js': {copy: 'tests/helpers/destroy-app.js'},
    'tests/helpers/module-for-acceptance.js': {copy: 'tests/helpers/module-for-acceptance.js'},
    'tests/helpers/resolver.js': {copy: 'tests/helpers/resolver.js'},
    'tests/helpers/start-app.js': {copy: 'tests/helpers/start-app.js'},
    'tests/unit/helpers/eq-test.js': {copy: 'tests/unit/helpers/eq-test.js'},
    'tests/unit/helpers/icon-test.js': {copy: 'tests/unit/helpers/icon-test.js'},
    'tests/unit/routes/about/route-test.js': {copy: 'tests/unit/routes/about/route-test.js'},

    '.bowerrc': {copy: '.bowerrc'},
    '.editorconfig': {copy: '.editorconfig'},
    '.ember-cli': {copy: '.ember-cli'},
    '.gitignore': {copy: '.gitkeep'},
    '.jshintrc': {copy: '.jshintrc'},
    '.travis.yml': {copy: '.travis.yml'},
    '.watchmanconfig': {copy: '.watchmanconfig'},

    'README.md': {copy: 'README.md'},
    'bower.json': {copy: 'bower.json'},
    'ember-cli-build.js': {copy: 'ember-cli-build.js'},
    'package.json': {copy: 'package.json'},
    'testem.js': {copy: 'testem.js'}
  }
};
